# Generated by Django 4.2.7 on 2025-04-25 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='İsim')),
                ('dogum_tarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('profil_resmi', models.ImageField(upload_to='profil_resimleri/', verbose_name='Profil Resmi')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
    ]
